# Generated by Django 4.2.7 on 2024-01-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_notes_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='note',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='notes',
            name='user',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
