# Generated by Django 4.2.7 on 2024-01-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quote_amount',
            new_name='pricing',
        ),
        migrations.AddField(
            model_name='quote',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
