# Generated by Django 4.2.7 on 2024-01-13 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_rename_quote_amount_quote_pricing_quote_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='pricing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.pricing'),
        ),
    ]
