# Generated by Django 4.2.7 on 2024-01-13 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_quote_pricing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='pricing',
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('CAD', 'CAD'), ('MXN', 'MXN'), ('USA', 'USA')], default='CAD', max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Expire', 'Expire'), ('Active', 'Active')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='quote',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Pricing',
        ),
    ]
